[build]
builder = "DOCKERFILE"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:${PORT:-8080}"

# These should be set in Railway dashboard as environment variables
# ConnectionStrings__DefaultConnection = "Host=...; Database=...; Username=...; Password=..."
# ConnectionStrings__Redis = "..."
# Stytch__ProjectId = "project-test-602a83cb-068f-4dd4-a473-0bb708335ee6"
# Stytch__ProjectSecret = "..."
# Stytch__PublicToken = "public-token-test-92b06025-3b67-4193-a934-54b95bb5bbcb"
# Jwt__SecretKey = "... (minimum 32 characters)"
# Stripe__SecretKey = "sk_test_..."
# Stripe__PublishableKey = "pk_test_..."