[build]
builder = "DOCKERFILE"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:${PORT:-8080}"

# These should be set in Railway dashboard as environment variables:
# ConnectionStrings__DefaultConnection = "Host=...; Database=...; Username=...; Password=..."
# ConnectionStrings__Redis = "redis.railway.internal:6379,password=YOUR_REDIS_PASSWORD"
# Note: Railway provides redis://default:password@host:port format, but StackExchange.Redis prefers host:port,password=xxx
# Stytch__ProjectId = "project-test-..."
# Stytch__ProjectSecret = "secret-test-..."
# Stytch__PublicToken = "public-token-test-..."
# Jwt__SecretKey = "... (minimum 32 characters)"
# Stripe__SecretKey = "sk_test_..."
# Stripe__PublishableKey = "pk_test_..."