version: '3.8'

networks:
  fermentum:
    name: fermentum

services:
  # Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: fermentum-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/ssl:/etc/nginx/ssl:ro
    depends_on:
      - fermentum-api
      - ui-user
      - ui-admin
    networks:
      - fermentum

  # Database
  infra-postgres:
    image: postgres:15-alpine
    container_name: infra-postgres
    environment:
      POSTGRES_DB: fermentum
      POSTGRES_USER: fermentum
      POSTGRES_PASSWORD: dev_password_123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./infrastructure/data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - fermentum
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fermentum"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NATS Messaging
  infra-nats:
    image: nats:2.10-alpine
    container_name: infra-nats
    command:
      - "--jetstream"
      - "--store_dir=/data"
      - "--http_port=8222"
    volumes:
      - ./infrastructure/data/nats:/data
    ports:
      - "4222:4222"  # NATS port
      - "8222:8222"  # HTTP monitoring
    networks:
      - fermentum

  # Redis (for session storage, caching)
  infra-redis:
    image: redis:7-alpine
    container_name: infra-redis
    command: redis-server --appendonly yes
    volumes:
      - ./infrastructure/data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - fermentum
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fermentum.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./infrastructure/data/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      infra-postgres:
        condition: service_healthy
    networks:
      - fermentum

  # Main Fermentum API Service
  fermentum-api:
    build:
      context: .
      dockerfile: services/fermentum-api/Dockerfile
    container_name: fermentum-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_HTTPS_PORT: ""
      Kestrel__Endpoints__Http__Url: "http://+:80"
      Stripe__SecretKey: sk_test_your_stripe_secret_key_here
      ConnectionStrings__DefaultConnection: "Host=infra-postgres;Port=5432;Database=fermentum;Username=fermentum;Password=dev_password_123"
      ConnectionStrings__Redis: "infra-redis:6379"
    ports:
      - "5001:80"
    depends_on:
      infra-postgres:
        condition: service_healthy
      infra-redis:
        condition: service_healthy
    networks:
      - fermentum
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin Frontend
  ui-admin:
    build:
      context: .
      dockerfile: ui/admin/Dockerfile
    container_name: ui-admin
    environment:
      VITE_API_URL: https://api.fermentum.dev/api
    ports:
      - "3000:80"
    depends_on:
      - fermentum-api
    networks:
      - fermentum
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Frontend (Main App)
  ui-user:
    build:
      context: .
      dockerfile: ui/user/Dockerfile
    container_name: ui-user
    environment:
      VITE_API_URL: https://api.fermentum.dev/api
    ports:
      - "3001:80"
    depends_on:
      - fermentum-api
    networks:
      - fermentum
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  nats_data: