[build]
root = "services/fermentum-api"
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
# ASPNETCORE_URLS is set at service level to use Railway's dynamic PORT variable
