tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

  certificates:
    - certFile: /etc/traefik/dynamic/localhost.crt
      keyFile: /etc/traefik/dynamic/localhost.key
      stores:
        - default
    - certFile: /etc/traefik/dynamic/fermentum.dev.crt
      keyFile: /etc/traefik/dynamic/fermentum.dev.key
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/dynamic/fermentum.dev.crt
        keyFile: /etc/traefik/dynamic/fermentum.dev.key